kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: palantir-operator-cpd-admin-sa
  labels:
    app.kubernetes.io/name: "palantir-operator"
    app.kubernetes.io/managed-by: "palantir.com"
    app.kubernetes.io/instance: "palantir-operator"
subjects:
- kind: ServiceAccount
  name: cpd-admin-sa
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: palantir-operator
