apiVersion: v1
kind: ServiceAccount
metadata:
  name: palantir-operator
  labels:
    app.kubernetes.io/name: "palantir-operator"
    app.kubernetes.io/managed-by: "palantir.com"
    app.kubernetes.io/instance: "palantir-operator"
